// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_jH7YJrxdQjsou39-t5sfaLV2BU94-t4',
    appId: '1:922759140726:android:96db213fc5a8d3f5469657',
    messagingSenderId: '922759140726',
    projectId: 'social-app-11fa2',
    storageBucket: 'social-app-11fa2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmHqH3kdzOJGpqr8vsd4oJvTJYVFK9ejQ',
    appId: '1:922759140726:ios:346700a2940677ed469657',
    messagingSenderId: '922759140726',
    projectId: 'social-app-11fa2',
    storageBucket: 'social-app-11fa2.appspot.com',
    androidClientId: '922759140726-7lr5kpkdp5e3egvr5ai07g45ivpisb0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalSystem',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwNMBrLvzio7F9Y6jya9W3EV6UqeYcTZk',
    appId: '1:922759140726:web:6657c8a446776430469657',
    messagingSenderId: '922759140726',
    projectId: 'social-app-11fa2',
    authDomain: 'social-app-11fa2.firebaseapp.com',
    storageBucket: 'social-app-11fa2.appspot.com',
    measurementId: 'G-2164RYT3P4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmHqH3kdzOJGpqr8vsd4oJvTJYVFK9ejQ',
    appId: '1:922759140726:ios:346700a2940677ed469657',
    messagingSenderId: '922759140726',
    projectId: 'social-app-11fa2',
    storageBucket: 'social-app-11fa2.appspot.com',
    androidClientId: '922759140726-7lr5kpkdp5e3egvr5ai07g45ivpisb0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwNMBrLvzio7F9Y6jya9W3EV6UqeYcTZk',
    appId: '1:922759140726:web:25b060cacdb6e6c7469657',
    messagingSenderId: '922759140726',
    projectId: 'social-app-11fa2',
    authDomain: 'social-app-11fa2.firebaseapp.com',
    storageBucket: 'social-app-11fa2.appspot.com',
    measurementId: 'G-3K6KJPFV8X',
  );

}