class Governments {
  static List<String> governments = [
    'government.All',
    'government.Cairo',
    'government.Giza',
    'government.Alexandria',
    'government.Dakahlia',
    'government.Qalyubia',
    'government.Gharbia',
    'government.Monufia',
    'government.KafrElSheikh',
    'government.Damietta',
    'government.PortSaid',
    'government.Ismailia',
    'government.Suez',
    'government.Sharqia',
    'government.Qalyubia',
    'government.Matrouh',
    'government.Sohag',
    'government.Qena',
    'government.Aswan',
    'government.Asyut',
    'government.BeniSuef',
    'government.Luxor',
    'government.Red Sea',
    'government.NewValley',
    'government.Fayoum',
    'government.Minya',
    'government.North Sini',
    'government.South Sini',
  ];
  static List<String> allGovernments = [
    'All',
    'Cairo',
    'Giza',
    'Alexandria',
    'Dakahlia',
    'Qalyubia',
    'Gharbia',
    'Menoufia',
    'Kafr El Sheikh',
    'Damietta',
    'Port Said',
    'Ismailia',
    'Suez',
    'Sharqia',
    'Qalyubia',
    'Matrouh',
    'Sohag',
    'Qena',
    'Aswan',
    'Asyut',
    'Beni Suef',
    'Luxor',
    'Red Sea',
    'New Valley',
    'Fayoum',
    'Minya',
    'North Sinai',
    'South Sinai',
  ];
  //  "Shoupra" : "Shoupra",
  //       "ShoubraElKheima" : "Shoubra El Kheima",
  //       "Helwan" : "Helwan",
  //       "Maadi" : "Maadi",
  //       "Nasr City" : "Nasr City",
  //       "Haram" : "Haram",
  //       "Dokki" : "Dokki",
  //       "Mohandessin" : "Mohandessin",
  //       "Zamalek" : "Zamalek",
  //       "New Cairo" : "New Cairo",
  //       "October" : "October",
  //       "Ain Shams" : "Ain Shams",
  //       "ElMarg" : "El Marg",
  //       "El Matarya" : "El Matarya",
  //       "El Tahrir" : "El Tahrir",
  //       "El Nozha" : "El Nozha",
  //       "El Zamalek" : "El Zamalek",
  //       "El Shorouk" : "El Shorouk",
  //       "El Obour" : "El Obour",
  //       "El Rehab" : "El Rehab",
  //       "Tanta" : "Tanta",
  //       "Tokh" : "Tokh",
  //       "Kafr El Dawar" : "Kafr El Dawar",
  //       "Heliopolis" : "Heliopolis",
  //       "El Khosous" : "El Khosous",
  //       "El Mokattam" : "El Mokattam",
  //       "El Salam" : "El Salam",
  //       "Ekhmim" : "Ekhmim",
  //       "Tahta" : "Tahta",
  //       "Tema" : "Tema",
  //       "Banha" : "Banha",
  //       "Shattoura" : "Shattoura",
  //       "Abou Tesht" : "Abou Tesht",
  //       "Nagaa Hamadi" : "Nagaa Hamadi",
  //       "Esna" : "Esna",
  //       "Edfu" : "Edfu",
  //       "Abou Simble" : "Abou Simble",
  //       "Malawi" : "Malawi",
  //       "Maghagha" : "Maghagha"
  static List<String> cities = [
    'city.All',
    'city.Shoupra',
    'city.Nasr City',
    'city.Zamalek',
    'city.Tanta',
    'city.El Marg',
    'city.El Tahrir',
    'city.El Nozha',
    'city.El Shorouk',
    'city.El Obour',
    'city.El Rehab',
    'city.El Salam',
    'city.El Khosous',
    'city.El Mokattam',
    'city.Tahta',
    'city.Abou Tesht',
    'city.Nagaa Hamadi',
    'city.Esna',
    'city.Edfu',
    'city.Abou Simble',
    'city.Malawi',
    'city.Maghagha',
    'city.ShoubraElKheima',
    'city.Helwan',
    'city.Maadi',
    'city.Dokki',
    'city.Mohandessin',
    'city.El Zamalek',
    'city.New Cairo',
    'city.October',
    'city.Ain Shams',
    'city.El Matarya'
  ];
  static List<String> citiesList = [
    'All',
    'Shoupra',
    'Nasr City',
    'Zamalek',
    'Tanta',
    'El Marg',
    'El Tahrir',
    'El Nozha',
    'El Shorouk',
    'El Obour',
    'El Rehab',
    'El Salam',
    'El Khosous',
    'El Mokattam',
    'Tahta',
    'Abou Tesht',
    'Nagaa Hamadi',
    'Esna',
    'Edfu',
    'Abou Simble',
    'Malawi',
    'Maghagha',
    'ShoubraElKheima',
    'Helwan',
    'Maadi',
    'Dokki',
    'Mohandessin',
    'El Zamalek',
    'New Cairo',
    'October',
    'Ain Shams',
    'El Matarya'
  ];
}
