class Governments {
  static List<String> governments = [
    'government.All',
    'government.Cairo',
    'government.Giza',
    'government.Alexandria',
    'government.Dakahlia',
    'government.Qalyubia',
    'government.Gharbia',
    'government.Menoufia',
    'government.Kafr El Sheikh',
    'government.Damietta',
    'government.Port Said',
    'government.Ismailia',
    'government.Suez',
    'government.Sharqia',
    'government.Qalyubia',
    'government.Matrouh',
    'government.Sohag',
    'government.Qena',
    'government.Aswan',
    'government.Asyut',
    'government.Beni Suef',
    'government.Luxor',
    'government.Red Sea',
    'government.New Valley',
    'government.Fayoum',
    'government.Minya',
    'government.North Sinai',
    'government.South Sinai',
  ];
  static List<String> allGovernments = [
    'All',
    'Cairo',
    'Giza',
    'Alexandria',
    'Dakahlia',
    'Qalyubia',
    'Gharbia',
    'Menoufia',
    'Kafr El Sheikh',
    'Damietta',
    'Port Said',
    'Ismailia',
    'Suez',
    'Sharqia',
    'Qalyubia',
    'Matrouh',
    'Sohag',
    'Qena',
    'Aswan',
    'Asyut',
    'Beni Suef',
    'Luxor',
    'Red Sea',
    'New Valley',
    'Fayoum',
    'Minya',
    'North Sinai',
    'South Sinai',
  ];
}
