class Specialities {
  static const List<String> list = [
    "specialities.All",
    "specialities.Dentist",
    "specialities.Cardiologist",
    "specialities.Neurologist",
    "specialities.GeneralPhysician",
    "specialities.Surgeon",
    "specialities.Dermatologist",
    "specialities.Ophthalmologist",
    "specialities.Gynecologist",
    "specialities.GynaecologistAndInfertility",
    "specialities.EarNoseAndThroat",
    "specialities.Hepatologist",
    "specialities.Respiratorist",
    "specialities.Orthopedic",
    "specialities.InternalMedicine",
    "specialities.Orthopedics",
    "specialities.Urologist",
    "specialities.PediatricsNewPorn",
    "specialities.Psychiatry",
    "specialities.GynecologistInfertility",
    "specialities.GastroenterologistEndoscopy",
    "specialities.Audiologist",
    "specialities.AllergyImmunologist",
    "specialities.AndrologistMaleInfertility",
    "specialities.DiabetesEndocrinologist",
    "specialities.Nephrologist",
    "specialities.Geriatrics",
    "specialities.Plastic",
    "specialities.Rheumatologist",
    "specialities.Spinal",
    "specialities.DietitianNutrition",
    "specialities.Physiotherapy",
    "specialities.Phoniatrics",
    "specialities.Pediatric",
    "specialities.ObsityLaparoscopic",
    "specialities.Oncologist",
    "specialities.GeneralSurgery",
  ];
  static List<String> specialities = [
    "All",
    "Dentist",
    "Cardiologist",
    "Neurologist",
    "General Physician",
    "Surgeon",
    "Dermatologist",
    "Ophthalmologist",
    "Gynecologist",
    "Gynaecologist And Infertility",
    "Ear, Nose And Throat",
    "Hepatologist",
    "Respiratorist",
    "Orthopedic",
    "Internal Medicine",
    "Orthopedics",
    "Urologist",
    "Pediatrics And New Porn",
    "Psychiatry",
    "Gynecologist And Infertility",
    "Gastroenterologist And Endoscopy",
    "Audiologist",
    "Allergy And Immunologist",
    "Andrologist And Male Infertility",
    "Diabetes And Endocrinologist",
    "Nephrologist",
    "Geriatrics",
    "Plastic Surgeon",
    "Rheumatologist",
    "Spinal Surgeon",
    "Dietitian And Nutritionist",
    "Physiotherapy",
    "Phoniatrics",
    "Pediatrician",
    "Obsity And Laparoscopic",
    "General Surgery"
  ];
}
