class Specialities {
  static const List<String> list = [
    "specialities.All",
    "specialities.Dentist",
    "specialities.Cardiologist",
    "specialities.Neurologist",
    "specialities.General Physician",
    "specialities.Surgeon",
    "specialities.Dermatologist",
    "specialities.Ophthalmologist",
    "specialities.Gynecologist",
    "specialities.Gynaecologist And Infertility",
    "specialities.Ear, Nose And Throat",
    "specialities.Hepatologist",
    "specialities.Respiratorist",
    "specialities.Orthopedic",
    "specialities.Internal Medicine",
    "specialities.Orthopedics",
    "specialities.Urologist",
    "specialities.Pediatrics And New Porn",
    "specialities.Psychiatry",
    "specialities.Gynecologist And Infertility",
    "specialities.Gastroenterologist And Endoscopy",
    "specialities.Audiologist",
    "specialities.Allergy And Immunologist",
    "specialities.Andrologist And Male Infertility",
    "specialities.Diabetes And Endocrinologist",
    "specialities.Nephrologist",
    "specialities.Geriatrics",
    "specialities.Plastic",
    "specialities.Rheumatologist",
    "specialities.Spinal",
    "specialities.Dietitian And Nutrition",
    "specialities.Physiotherapy",
    "specialities.Phoniatrics",
    "specialities.Pediatric",
    "specialities.Obsity And Laparoscopic",
    "specialities.Oncologist",
    "specialities.General Surgery",
  ];
  static List<String> specialities = [
    "All",
    "Dentist",
    "Cardiologist",
    "Neurologist",
    "General Physician",
    "Surgeon",
    "Dermatologist",
    "Ophthalmologist",
    "Gynecologist",
    "Gynaecologist And Infertility",
    "Ear, Nose And Throat",
    "Hepatologist",
    "Respiratorist",
    "Orthopedic",
    "Internal Medicine",
    "Orthopedics",
    "Urologist",
    "Pediatrics And New Porn",
    "Psychiatry",
    "Gynecologist And Infertility",
    "Gastroenterologist And Endoscopy",
    "Audiologist",
    "Allergy And Immunologist",
    "Andrologist And Male Infertility",
    "Diabetes And Endocrinologist",
    "Nephrologist",
    "Geriatrics",
    "Plastic Surgeon",
    "Rheumatologist",
    "Spinal Surgeon",
    "Dietitian And Nutritionist",
    "Physiotherapy",
    "Phoniatrics",
    "Pediatrician",
    "Obsity And Laparoscopic",
    "General Surgery"
  ];

  static const List<String> labSpecialities = [
    "All",
    "Medical",
    "Radiology",
    "Nutrition",
    "Genetic Testing"
  ];
  static const List<String> labList = [
    "specialities.All",
    "specialities.Medical",
    "specialities.Radiology",
    "specialities.Nutrition",
    "specialities.Genetic Testing"
  ];
}
